title: Pure Studios # your name (or website title) here
logo: "/images/portrait.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <br>Indie Game Developer<br>
  <br>
  <a href="https://www.youtube.com/@PureCoverage">LinkedIn</a> 

theme: jekyll-theme-minimal
google_analytics: UA-000000-0 
